services:
  api:
    build: .
    container_name: dailyfin
    ports:
      - "8088:8088"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./src/dailyfin/frontend/static:/app/frontend/static
      - ./src:/app/src
    restart: unless-stopped
      
    command: >
      sh -c "PYTHONPATH=src uvicorn dailyfin.main:app --host 0.0.0.0 --port 8088 --reload"




  db:
    image: mysql:8.0
    container_name: dailyfin-db
    restart: unless-stopped
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: account_db
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    volumes:
      - dbdata:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  dbdata:
